import { chromium, type FullConfig } from '@playwright/test';

// AUTO-GENERATED by the test harness — do not edit. Re-establishes a fresh
// authenticated session immediately before the suite runs so a short-lived
// OAuth/XSUAA session (e.g. SAP BTP) cannot expire between generation and run.

const ENTRY_URL = "https://app.test/single";
const STATE_PATH = '.auth/storageState.json';
const USER_SEL =
  '#j_username, input[name="j_username"], input[type="email"], input[name="username"], input[autocomplete="username"]';
const PASS_SEL =
  '#j_password, input[name="j_password"], input[type="password"], input[autocomplete="current-password"]';

export default async function globalSetup(_config: FullConfig) {
  const username = process.env.TARGET_USERNAME?.trim();
  const password = process.env.TARGET_PASSWORD?.trim();
  const idp = process.env.TARGET_IDP?.trim();
  const startUrl = process.env.TARGET_LOGIN_URL?.trim() || ENTRY_URL;
  if (!username || !password) {
    console.warn('[global-setup] TARGET_USERNAME/TARGET_PASSWORD not set — skipping fresh login.');
    return;
  }

  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  const idle = () => page.waitForLoadState('networkidle').catch(() => {});
  try {
    await page.goto(startUrl, { waitUntil: 'domcontentloaded' });
    await idle();

    // (1) App landing page: click a "Login with BTP"/"Login" entry point when no
    //     username field is shown yet.
    if ((await page.locator(USER_SEL).count()) === 0) {
      const entry = page
        .getByRole('button', { name: /login with btp|log ?in|sign in/i })
        .or(page.getByRole('link', { name: /login with btp|log ?in|sign in/i }));
      if (await entry.count()) { await entry.first().click(); await idle(); }
    }

    // (2) Identity-provider chooser: pick the configured provider (never cycle).
    if (idp) {
      const choice = page
        .getByRole('link', { name: idp })
        .or(page.getByRole('button', { name: idp }));
      if (await choice.count()) { await choice.first().click(); await idle(); }
    }

    // (3) Username, then password — handling a two-step username->Continue->password flow.
    const user = page.locator(USER_SEL).first();
    await user.waitFor({ timeout: 15000 });
    await user.fill(username);

    let pass = page.locator(PASS_SEL).first();
    if ((await page.locator(PASS_SEL).count()) === 0 || !(await pass.isVisible().catch(() => false))) {
      const cont = page.getByRole('button', { name: /continue|next|log on|sign in|submit/i });
      if (await cont.count()) await cont.first().click(); else await user.press('Enter');
      await idle();
      pass = page.locator(PASS_SEL).first();
    }
    await pass.waitFor({ timeout: 15000 });
    await pass.fill(password);

    // (4) Submit and wait to land back in the app.
    const submit = page
      .getByRole('button', { name: /log on|sign in|log ?in|continue|submit/i })
      .or(page.locator('input[type="submit"], button[type="submit"]'));
    if (await submit.count()) await submit.first().click(); else await pass.press('Enter');
    await idle();
    await page.waitForTimeout(2000);

    await context.storageState({ path: STATE_PATH });
    console.log('[global-setup] fresh auth state saved ->', STATE_PATH, '| final url:', page.url());
  } catch (err) {
    console.error('[global-setup] login failed; leaving existing storage state:', err instanceof Error ? err.message : String(err));
  } finally {
    await browser.close();
  }
}
