import { chromium, type FullConfig } from '@playwright/test';

// AUTO-GENERATED by the test harness — do not edit. Re-establishes a fresh
// authenticated session immediately before the suite runs so a short-lived
// OAuth/XSUAA session (e.g. SAP BTP) cannot expire between generation and run.

const ENTRY_URL = "https://sapbtp-roi-calculator-stage.cfapps.eu10-004.hana.ondemand.com";
const STATE_PATH = '.auth/storageState.json';
const USER_SEL =
  '#j_username, input[name="j_username"], input[type="email"], input[name="username"], input[autocomplete="username"]';
const PASS_SEL =
  '#j_password, input[name="j_password"], input[type="password"], input[autocomplete="current-password"]';

export default async function globalSetup(_config: FullConfig) {
  const username = process.env.TARGET_USERNAME?.trim();
  const password = process.env.TARGET_PASSWORD?.trim();
  const idp = process.env.TARGET_IDP?.trim();
  const startUrl = process.env.TARGET_LOGIN_URL?.trim() || ENTRY_URL;
  if (!username || !password) {
    console.warn('[global-setup] TARGET_USERNAME/TARGET_PASSWORD not set — skipping fresh login.');
    return;
  }

  // The host the app is actually served from (e.g. *.cfapps.*.hana.ondemand.com) —
  // distinct from the IdP hosts (accounts.sap.com, *.authentication.*) we transit
  // during login. Landing back here, with a cookie for it, is the only proof the
  // OAuth round-trip closed.
  const appHost = new URL(startUrl).hostname;
  // Standard cookie domain-match: does this cookie get sent to the app host? IdP
  // cookies (different subdomain branch) correctly fail this test.
  const domainMatchesApp = (rawDomain: string) => {
    const d = rawDomain.replace(/^\./, '');
    return appHost === d || appHost.endsWith('.' + d);
  };
  // Edge/CDN/bot-protection and analytics cookies are seeded on the app host on the
  // FIRST page load — before, and regardless of, login. Their presence proves we
  // reached the host, NOT that we authenticated, so they must NOT satisfy the guard
  // below. Without this, a Cloudflare-fronted app (which sets __cf_bm / cf_clearance
  // and a __dpl deploy cookie on the bare app domain) fakes a logged-in state and
  // every test then runs against the login page. Match by exact reserved name.
  const NON_AUTH_COOKIE =
    /^(__cf_bm|cf_clearance|__cflb|__cfruid|__cfwaitingroom|__cfduid|__dpl|__Secure-__dpl|_ga|_gid|_gat|_gcl_au|_fbp|ai_user|ai_session)$/i;
  // A cookie counts as proof of a session only if it is on the app host AND is not a
  // known infrastructure/analytics cookie.
  const isAppSessionCookie = (c) =>
    domainMatchesApp(c.domain) && !NON_AUTH_COOKIE.test(c.name);
  // Many SPA logins keep NO session cookie at all — they store a JWT in
  // localStorage and send it as a bearer header (e.g. Supabase 'sb-<ref>-auth-token',
  // Firebase, generic access/auth tokens). Playwright's storageState captures
  // localStorage too, and use.storageState restores it, so such a session is fully
  // reusable — we just have to RECOGNISE it. Note: pre-login anonymous keys (e.g.
  // '__lovable_session') must NOT match, or we'd accept a logged-out state.
  const AUTH_LOCALSTORAGE =
    /(^sb-.*-auth-token$)|access[_-]?token|auth[_-]?token|id[_-]?token|supabase|firebase:authuser/i;

  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  // SAP IdP login pages frequently never reach 'networkidle' (long-poll/keepalive),
  // so bound the wait — an unbounded idle() silently burns the default 30s per call.
  const idle = () => page.waitForLoadState('networkidle', { timeout: 7000 }).catch(() => {});
  const passField = () => page.locator(PASS_SEL).first();
  const passVisible = () =>
    page.locator(PASS_SEL).first().isVisible().catch(() => false);
  let landed = false;
  try {
    await page.goto(startUrl, { waitUntil: 'domcontentloaded' });
    await idle();

    // (1) App landing page: click a "Login with BTP"/"Login" entry point when no
    //     username field is shown yet.
    if ((await page.locator(USER_SEL).count()) === 0) {
      const entry = page
        .getByRole('button', { name: /login with btp|log ?in|sign in/i })
        .or(page.getByRole('link', { name: /login with btp|log ?in|sign in/i }));
      if (await entry.count()) { await entry.first().click(); await idle(); }
    }

    // (2) Identity-provider chooser: pick the configured provider by its EXACT label.
    //     SAP tenants often list several providers whose names share words
    //     ("Default Identity Provider" vs "Tarento Identity Provider") — a substring
    //     match could select the wrong one, and wrong-provider attempts can lock the
    //     account, so require an exact match and never cycle.
    if (idp) {
      const choice = page
        .getByRole('link', { name: idp, exact: true })
        .or(page.getByRole('button', { name: idp, exact: true }));
      if (await choice.count()) {
        await choice.first().click();
        // Wait for the chosen provider's form, not a flaky networkidle.
        await page.locator(USER_SEL).first().waitFor({ timeout: 15000 }).catch(() => {});
        await idle();
      }
    }

    // (3) Username, then password. Two shapes seen on SAP tenants:
    //       - single page: #j_username + #j_password together (fill both, submit once)
    //       - two step:    username -> Continue/Next -> password on the next page
    const user = page.locator(USER_SEL).first();
    await user.waitFor({ timeout: 15000 });
    await user.fill(username);

    if (!(await passVisible())) {
      // Two-step flow: advance past the username page, then WAIT for the password
      // field to actually render before filling (the old code raced the redirect).
      const cont = page.getByRole('button', { name: /continue|next|log on|sign in|submit/i });
      if (await cont.count()) await cont.first().click(); else await user.press('Enter');
      await idle();
      await passField().waitFor({ timeout: 20000 });
    }
    await passField().waitFor({ timeout: 15000 });
    await passField().fill(password);

    // (4) Submit, then wait for an authenticated session to actually MATERIALISE.
    //     Two shapes, handled by one poll:
    //       - redirect SSO (SAP BTP/XSUAA): multi-hop app -> BTP -> IdP -> back, the
    //         session lands as a COOKIE on the app host.
    //       - SPA login (e.g. Supabase/Lovable): an XHR sets a JWT in localStorage
    //         with NO navigation, so a waitForURL(appHost) check is a no-op that
    //         resolves before the token is written — snapshotting too early.
    //     Polling the real session state (cookie OR localStorage token) covers both
    //     and waits as long as either takes.
    const submit = page
      .getByRole('button', { name: /log on|sign in|log ?in|continue|submit/i })
      .or(page.locator('input[type="submit"], button[type="submit"]'));
    if (await submit.count()) await submit.first().click(); else await passField().press('Enter');

    const hasSessionNow = async () => {
      const cookieOk = (await context.cookies()).some(isAppSessionCookie);
      if (cookieOk) return true;
      const lsKeys = await page
        .evaluate(() => { try { return Object.keys(localStorage); } catch { return []; } })
        .catch(() => []);
      return lsKeys.some((k) => AUTH_LOCALSTORAGE.test(k));
    };
    const deadline = Date.now() + 30000;
    while (Date.now() < deadline) {
      if (await hasSessionNow()) break;
      await page.waitForTimeout(500);
    }
    await idle();

    // (5) Guard: only persist a state the app will actually treat as logged in —
    //     a real session cookie (NOT a CDN/bot cookie; see NON_AUTH_COOKIE) OR a
    //     localStorage auth token (see AUTH_LOCALSTORAGE).
    const state = await context.storageState({ path: STATE_PATH });
    const sessionCookies = (state.cookies || []).filter(isAppSessionCookie);
    const lsAuthKeys = (state.origins || [])
      .flatMap((o) => (o.localStorage || []).map((l) => l.name))
      .filter((k) => AUTH_LOCALSTORAGE.test(k));
    landed = sessionCookies.length > 0 || lsAuthKeys.length > 0;
    if (landed) {
      console.log('[global-setup] fresh auth state saved ->', STATE_PATH,
        '| session cookie(s):', sessionCookies.map((c) => c.name).join(', ') || '(none)',
        '| localStorage token(s):', lsAuthKeys.join(', ') || '(none)',
        '| final url:', page.url());
    } else {
      const cookieNames = (state.cookies || []).map((c) => c.name).join(', ') || '(none)';
      const lsNames = (state.origins || []).flatMap((o) => (o.localStorage || []).map((l) => l.name)).join(', ') || '(none)';
      console.error('[global-setup] login did not complete — no session cookie and no localStorage auth token. ' +
        'cookies:', cookieNames, '| localStorage:', lsNames,
        '| (wrong credentials, or the login flow was not recognised) | final url:', page.url());
    }
  } catch (err) {
    console.error('[global-setup] login failed:', err instanceof Error ? err.message : String(err), '| final url:', page.url());
  } finally {
    await browser.close();
  }

  // Abort the whole run rather than execute a suite that would test the login page.
  if (!landed) {
    throw new Error(
      '[global-setup] auth did not complete — no session cookie or localStorage token for app host ' + appHost +
      '. Aborting instead of running tests against the login page. ' +
      'Check TARGET_USERNAME/TARGET_PASSWORD/TARGET_IDP and the login flow.'
    );
  }
}
